# Generated by Django 3.0.8 on 2020-07-30 11:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='categoryModel',
            fields=[
                ('catId', models.AutoField(primary_key=True, serialize=False)),
                ('category', models.CharField(max_length=200)),
                ('last_modified', models.DateTimeField(auto_now_add=True)),
                ('posts', models.IntegerField(blank=True, default='0', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='firstModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(max_length=200)),
                ('receiver', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('last_modified', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='userModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_name', models.CharField(max_length=200)),
                ('l_name', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200, unique=True)),
                ('password', models.TextField()),
                ('password2', models.TextField()),
                ('last_modified', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='postModel',
            fields=[
                ('postId', models.AutoField(primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=200)),
                ('post_message', models.TextField()),
                ('location', models.CharField(blank=True, max_length=200, null=True)),
                ('category', models.CharField(max_length=200)),
                ('image', models.ImageField(blank=True, upload_to='uploads/')),
                ('last_modified', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='firstApp.userModel')),
            ],
        ),
        migrations.CreateModel(
            name='messagesModel',
            fields=[
                ('mId', models.AutoField(primary_key=True, serialize=False)),
                ('message', models.CharField(max_length=500)),
                ('last_modified', models.DateTimeField(auto_now_add=True)),
                ('catId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='firstApp.categoryModel')),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='firstApp.userModel')),
            ],
        ),
        migrations.CreateModel(
            name='commentModel',
            fields=[
                ('commentId', models.AutoField(primary_key=True, serialize=False)),
                ('user', models.CharField(max_length=200)),
                ('comment_message', models.TextField()),
                ('likes', models.IntegerField(blank=True, default='0', null=True)),
                ('dislike', models.IntegerField(blank=True, default='0', null=True)),
                ('last_modified', models.DateTimeField(auto_now_add=True)),
                ('postId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='firstApp.postModel')),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='firstApp.userModel')),
            ],
        ),
    ]
